#!/usr/bin/env Rscript

# ==============================================================================
# Mouse MASH MΦ
# Clean-B primary dataset
# Anti-inflammatory-MΦ Sham vs Tx deep analysis
# v4.12.0
# ==============================================================================
#
# INPUT
#   Clean-B RDS generated by v4.11.7
#
# PRIMARY QUESTION
#   What changes functionally within Anti-inflammatory-MΦ after transplantation?
#
# ANALYSIS
#   1) Sample-level SAFE pseudobulk (explicit Matrix::rowSums)
#   2) Sham vs Tx descriptive log2FC
#   3) Exploratory edgeR pseudobulk DE if edgeR is available
#   4) Key-gene sample-level plots
#   5) Curated functional-program pseudobulk scores
#   6) Optional Hallmark / Reactome GSEA if msigdbr + fgsea are available
#
# IMPORTANT
#   - Biological replicate = sample
#   - Sham1, Sham20 vs Tx17, Tx5
#   - n=2 vs 2; p/FDR are exploratory
#   - Effect size and replicate consistency are primary
#
# ==============================================================================

options(stringsAsFactors = FALSE)
set.seed(4120)

# ------------------------------------------------------------------------------
# 0. Paths
# ------------------------------------------------------------------------------

PROJECT_DATA_ROOT <- "/Volumes/SSD990_uenoy/scRNA_MASLD_MASH_pseudobulk"

INPUT_RDS <- file.path(
    PROJECT_DATA_ROOT,
    "Mouse_MASH_Mphi_RDS",
    "Mphi_cleaning_sensitivity_v4.11.7",
    "RDS",
    "Mouse_Mphi_Res2_Clean_B_v4.11.7.rds"
)

OUTPUT_DIR <- file.path(
    PROJECT_DATA_ROOT,
    "Mouse_MASH_Mphi_RDS",
    "CleanB_Anti_inflammatory_Mphi_ShamTx_v4.12.0"
)

FIG_DIR <- file.path(OUTPUT_DIR, "Figures")
TAB_DIR <- file.path(OUTPUT_DIR, "Tables")
PB_DIR  <- file.path(OUTPUT_DIR, "Pseudobulk")
LOG_DIR <- file.path(OUTPUT_DIR, "Logs")

dir.create(FIG_DIR, recursive = TRUE, showWarnings = FALSE)
dir.create(TAB_DIR, recursive = TRUE, showWarnings = FALSE)
dir.create(PB_DIR,  recursive = TRUE, showWarnings = FALSE)
dir.create(LOG_DIR, recursive = TRUE, showWarnings = FALSE)

ASSAY_USE <- "RNA"

SHAM_SAMPLES <- c(
    "Sham1",
    "Sham20"
)

TX_SAMPLES <- c(
    "Tx17",
    "Tx5"
)

TARGET_CLASS <- "Anti-inflammatory-Mphi"

CPM_PSEUDOCOUNT <- 1

# ------------------------------------------------------------------------------
# 1. Curated functional programs
# ------------------------------------------------------------------------------

PROGRAMS <- list(

    Anti_inflammatory = c(
        "Mrc1",
        "Cd163",
        "Il1rn",
        "Retnla",
        "Chil3",
        "Arg1",
        "Mertk",
        "Igf1",
        "Hmox1",
        "Klf4",
        "Maf"
    ),

    IL10_STAT3 = c(
        "Il10",
        "Il10ra",
        "Il10rb",
        "Jak1",
        "Tyk2",
        "Stat3",
        "Socs3",
        "Bcl3",
        "Il1rn"
    ),

    Efferocytosis = c(
        "Mertk",
        "Axl",
        "Mfge8",
        "Gas6",
        "Marco",
        "Cd36",
        "Lrp1",
        "C1qa",
        "C1qb",
        "C1qc"
    ),

    Repair_Resolution = c(
        "Mertk",
        "Axl",
        "Mfge8",
        "Gas6",
        "Igf1",
        "Hmox1",
        "Mmp12",
        "Mmp13",
        "Mmp14",
        "Plau"
    ),

    Fibrogenic = c(
        "Spp1",
        "Tgfb1",
        "Pdgfb",
        "Thbs1",
        "Lgals3",
        "Gpnmb",
        "Mmp12",
        "Mmp14",
        "Ctsb"
    ),

    Inflammatory = c(
        "Il1b",
        "Tnf",
        "Ccl2",
        "Ccl3",
        "Ccl4",
        "Cxcl10",
        "Nos2",
        "Cd80",
        "Cd86",
        "Stat1"
    ),

    Lipid_TREM2 = c(
        "Trem2",
        "Gpnmb",
        "Cd9",
        "Lpl",
        "Apoe",
        "Fabp5",
        "Abca1",
        "Plin2",
        "Ctsd"
    )
)

KEY_GENES <- unique(
    c(
        "Mrc1",
        "Cd163",
        "Il1rn",
        "Mertk",
        "Igf1",
        "Hmox1",
        "Maf",
        "Klf4",
        "Socs3",
        "Stat3",
        "Il10ra",
        "Il10rb",
        "Il1b",
        "Tnf",
        "Ccl2",
        "Spp1",
        "Tgfb1",
        "Pdgfb",
        "Trem2",
        "Gpnmb",
        "Cd9",
        "Lpl",
        "Apoe",
        "Mfge8",
        "Gas6"
    )
)

# ------------------------------------------------------------------------------
# 2. Packages
# ------------------------------------------------------------------------------

required_packages <- c(
    "Seurat",
    "SeuratObject",
    "Matrix",
    "dplyr",
    "tidyr",
    "tibble",
    "ggplot2",
    "patchwork",
    "scales"
)

missing_packages <- required_packages[
    !vapply(
        required_packages,
        requireNamespace,
        logical(1),
        quietly = TRUE
    )
]

if (length(missing_packages) > 0L) {
    stop(
        "Missing required package(s): ",
        paste(missing_packages, collapse = ", ")
    )
}

HAS_EDGER <- requireNamespace(
    "edgeR",
    quietly = TRUE
)

HAS_FGSEA <- requireNamespace(
    "fgsea",
    quietly = TRUE
)

HAS_MSIGDBR <- requireNamespace(
    "msigdbr",
    quietly = TRUE
)

suppressPackageStartupMessages({
    library(Seurat)
    library(SeuratObject)
    library(Matrix)
    library(dplyr)
    library(tidyr)
    library(tibble)
    library(ggplot2)
    library(patchwork)
    library(scales)
})

if (HAS_EDGER) {
    suppressPackageStartupMessages(
        library(edgeR)
    )
}

# ------------------------------------------------------------------------------
# 3. Helpers
# ------------------------------------------------------------------------------

msg <- function(...) {
    message(
        "[",
        format(
            Sys.time(),
            "%Y-%m-%d %H:%M:%S"
        ),
        "] ",
        paste0(...)
    )
}

first_existing <- function(
    x,
    candidates
) {

    hit <- candidates[
        candidates %in%
            x
    ]

    if (length(hit) == 0L) {
        return(
            NA_character_
        )
    }

    hit[[1]]
}

get_layer_safe <- function(
    object,
    assay,
    layer
) {

    x <- tryCatch(
        LayerData(
            object,
            assay = assay,
            layer = layer
        ),
        error = function(e) NULL
    )

    if (is.null(x)) {

        x <- tryCatch(
            GetAssayData(
                object,
                assay = assay,
                slot = layer
            ),
            error = function(e) NULL
        )
    }

    x
}

save_pdf <- function(
    filename,
    plot,
    width,
    height
) {

    ggsave(
        filename = file.path(
            FIG_DIR,
            filename
        ),
        plot = plot,
        device = cairo_pdf,
        width = width,
        height = height,
        units = "in",
        limitsize = FALSE
    )
}

calc_cpm <- function(
    count_matrix
) {

    lib <- colSums(
        count_matrix
    )

    if (any(lib <= 0)) {
        stop(
            "At least one pseudobulk library has zero total counts."
        )
    }

    sweep(
        count_matrix,
        2,
        lib / 1e6,
        "/"
    )
}

# ------------------------------------------------------------------------------
# 4. Load Clean-B
# ------------------------------------------------------------------------------

if (!file.exists(INPUT_RDS)) {

    stop(
        "Clean-B RDS not found:\n",
        INPUT_RDS
    )
}

msg(
    "Loading Clean-B: ",
    INPUT_RDS
)

mphi <- readRDS(
    INPUT_RDS
)

if (!inherits(
    mphi,
    "Seurat"
)) {
    stop(
        "Input is not a Seurat object."
    )
}

DefaultAssay(
    mphi
) <- ASSAY_USE

# ------------------------------------------------------------------------------
# 5. Metadata detection
# ------------------------------------------------------------------------------

meta_cols <- colnames(
    mphi@meta.data
)

SAMPLE_COL <- first_existing(
    meta_cols,
    c(
        "sample_4group",
        "sample",
        "sample_id",
        "orig.ident"
    )
)

CLASS_COL <- first_existing(
    meta_cols,
    c(
        "macrophage_class_Res2_v484",
        "macrophage_class_v484",
        "manual_class_v484",
        "macrophage_class"
    )
)

if (is.na(SAMPLE_COL)) {
    stop(
        "Sample metadata column not found."
    )
}

if (is.na(CLASS_COL)) {
    stop(
        "v4.8.4 macrophage class column not found."
    )
}

# ------------------------------------------------------------------------------
# 6. Retrieve counts and normalized RNA
# ------------------------------------------------------------------------------

counts <- get_layer_safe(
    mphi,
    ASSAY_USE,
    "counts"
)

data_norm <- get_layer_safe(
    mphi,
    ASSAY_USE,
    "data"
)

if (is.null(counts)) {
    stop(
        "RNA counts layer not found."
    )
}

if (is.null(data_norm)) {
    stop(
        "RNA normalized data layer not found."
    )
}

if (!identical(
    colnames(counts),
    colnames(mphi)
)) {
    stop(
        "Counts cell order does not match Seurat object."
    )
}

# ------------------------------------------------------------------------------
# 7. Extract Anti-inflammatory-MΦ and Sham/Tx only
# ------------------------------------------------------------------------------

meta <- mphi@meta.data %>%
    rownames_to_column(
        "cell"
    ) %>%
    transmute(
        cell = cell,
        sample = as.character(
            .data[[SAMPLE_COL]]
        ),
        macrophage_class = as.character(
            .data[[CLASS_COL]]
        )
    ) %>%
    mutate(
        condition = case_when(
            sample %in%
                SHAM_SAMPLES ~
                "Sham",

            sample %in%
                TX_SAMPLES ~
                "Tx",

            TRUE ~
                NA_character_
        )
    )

target_meta <- meta %>%
    filter(
        macrophage_class ==
            TARGET_CLASS,
        !is.na(condition)
    )

sample_counts <- target_meta %>%
    count(
        sample,
        condition,
        name = "n_cells"
    )

write.csv(
    sample_counts,
    file.path(
        TAB_DIR,
        "00_Anti_inflammatory_Mphi_cell_counts_by_sample_v4.12.0.csv"
    ),
    row.names = FALSE
)

print(
    sample_counts
)

if (!all(
    c(
        SHAM_SAMPLES,
        TX_SAMPLES
    ) %in%
        target_meta$sample
)) {

    stop(
        "One or more expected Sham/Tx samples have no Anti-inflammatory-MΦ cells."
    )
}

# ------------------------------------------------------------------------------
# 8. SAFE sample-level pseudobulk
# ------------------------------------------------------------------------------

sample_order <- c(
    SHAM_SAMPLES,
    TX_SAMPLES
)

pb_list <- vector(
    "list",
    length(sample_order)
)

names(pb_list) <- sample_order

pb_qc <- vector(
    "list",
    length(sample_order)
)

for (i in seq_along(sample_order)) {

    smp <- sample_order[[i]]

    cells <- target_meta$cell[
        target_meta$sample ==
            smp
    ]

    cells <- intersect(
        cells,
        colnames(counts)
    )

    if (length(cells) == 0L) {
        stop(
            "No target cells for sample: ",
            smp
        )
    }

    pb <- Matrix::rowSums(
        counts[
            ,
            cells,
            drop = FALSE
        ]
    )

    pb_list[[smp]] <- pb

    pb_qc[[i]] <- tibble(
        sample = smp,
        condition = ifelse(
            smp %in%
                SHAM_SAMPLES,
            "Sham",
            "Tx"
        ),
        n_cells = length(cells),
        library_size = sum(pb),
        mean_counts_per_cell =
            sum(pb) /
            length(cells)
    )
}

pb_counts <- do.call(
    cbind,
    pb_list
)

rownames(
    pb_counts
) <- rownames(
    counts
)

colnames(
    pb_counts
) <- sample_order

pb_qc <- bind_rows(
    pb_qc
)

write.csv(
    pb_qc,
    file.path(
        PB_DIR,
        "01_SAFE_pseudobulk_QC_v4.12.0.csv"
    ),
    row.names = FALSE
)

write.csv(
    data.frame(
        gene = rownames(
            pb_counts
        ),
        pb_counts,
        check.names = FALSE
    ),
    file.path(
        PB_DIR,
        "02_SAFE_pseudobulk_raw_counts_v4.12.0.csv"
    ),
    row.names = FALSE
)

# Hard check against accidental identical libraries
for (i in seq_len(
    ncol(pb_counts) - 1L
)) {

    for (j in (
        i + 1L
    ):ncol(pb_counts)) {

        if (identical(
            pb_counts[, i],
            pb_counts[, j]
        )) {

            stop(
                "Identical pseudobulk libraries detected: ",
                colnames(pb_counts)[[i]],
                " and ",
                colnames(pb_counts)[[j]]
            )
        }
    }
}

msg(
    "Pseudobulk QC passed: all 4 libraries are distinct."
)

# ------------------------------------------------------------------------------
# 9. CPM and descriptive Sham vs Tx effect size
# ------------------------------------------------------------------------------

pb_cpm <- calc_cpm(
    pb_counts
)

pb_log2cpm <- log2(
    pb_cpm +
        CPM_PSEUDOCOUNT
)

write.csv(
    data.frame(
        gene = rownames(
            pb_cpm
        ),
        pb_cpm,
        check.names = FALSE
    ),
    file.path(
        PB_DIR,
        "03_SAFE_pseudobulk_CPM_v4.12.0.csv"
    ),
    row.names = FALSE
)

mean_sham <- rowMeans(
    pb_cpm[
        ,
        SHAM_SAMPLES,
        drop = FALSE
    ]
)

mean_tx <- rowMeans(
    pb_cpm[
        ,
        TX_SAMPLES,
        drop = FALSE
    ]
)

descriptive_de <- tibble(
    gene = rownames(
        pb_cpm
    ),

    mean_CPM_Sham =
        as.numeric(
            mean_sham
        ),

    mean_CPM_Tx =
        as.numeric(
            mean_tx
        ),

    log2FC_Tx_vs_Sham =
        log2(
            (
                mean_tx +
                    CPM_PSEUDOCOUNT
            ) /
            (
                mean_sham +
                    CPM_PSEUDOCOUNT
            )
        )
) %>%
    arrange(
        desc(
            abs(
                log2FC_Tx_vs_Sham
            )
        )
    )

write.csv(
    descriptive_de,
    file.path(
        PB_DIR,
        "04_Anti_inflammatory_Mphi_Sham_vs_Tx_descriptive_DE_v4.12.0.csv"
    ),
    row.names = FALSE
)

# ------------------------------------------------------------------------------
# 10. Exploratory edgeR
# ------------------------------------------------------------------------------

edgeR_result <- NULL

if (HAS_EDGER) {

    group <- factor(
        c(
            "Sham",
            "Sham",
            "Tx",
            "Tx"
        ),
        levels = c(
            "Sham",
            "Tx"
        )
    )

    y <- edgeR::DGEList(
        counts = round(
            as.matrix(
                pb_counts
            )
        ),
        group = group
    )

    keep <- edgeR::filterByExpr(
        y,
        group = group
    )

    y <- y[
        keep,
        ,
        keep.lib.sizes = FALSE
    ]

    y <- edgeR::calcNormFactors(
        y
    )

    design <- model.matrix(
        ~ group
    )

    y <- edgeR::estimateDisp(
        y,
        design,
        robust = TRUE
    )

    fit <- edgeR::glmQLFit(
        y,
        design,
        robust = TRUE
    )

    qlf <- edgeR::glmQLFTest(
        fit,
        coef = 2
    )

    edgeR_result <- edgeR::topTags(
        qlf,
        n = Inf,
        sort.by = "PValue"
    )$table %>%
        rownames_to_column(
            "gene"
        ) %>%
        rename(
            edgeR_log2FC =
                logFC,
            edgeR_logCPM =
                logCPM,
            edgeR_F =
                F,
            edgeR_PValue =
                PValue,
            edgeR_FDR =
                FDR
        ) %>%
        left_join(
            descriptive_de,
            by = "gene"
        )

    write.csv(
        edgeR_result,
        file.path(
            PB_DIR,
            "05_Anti_inflammatory_Mphi_Sham_vs_Tx_edgeR_exploratory_v4.12.0.csv"
        ),
        row.names = FALSE
    )

    msg(
        "edgeR exploratory pseudobulk DE completed."
    )

} else {

    msg(
        "edgeR is not installed; exploratory statistical DE skipped."
    )
}

# ------------------------------------------------------------------------------
# 11. Key-gene sample-level pseudobulk table
# ------------------------------------------------------------------------------

KEY_GENES_USE <- intersect(
    KEY_GENES,
    rownames(
        pb_log2cpm
    )
)

key_gene_long <- as.data.frame(
    pb_log2cpm[
        KEY_GENES_USE,
        ,
        drop = FALSE
    ]
) %>%
    rownames_to_column(
        "gene"
    ) %>%
    pivot_longer(
        cols = -gene,
        names_to = "sample",
        values_to = "log2CPM"
    ) %>%
    mutate(
        condition = ifelse(
            sample %in%
                SHAM_SAMPLES,
            "Sham",
            "Tx"
        )
    )

write.csv(
    key_gene_long,
    file.path(
        TAB_DIR,
        "06_key_gene_sample_level_log2CPM_v4.12.0.csv"
    ),
    row.names = FALSE
)

# ------------------------------------------------------------------------------
# 12. Key-gene plot with all four biological samples
# ------------------------------------------------------------------------------

p_key_gene <- ggplot(
    key_gene_long,
    aes(
        x = condition,
        y = log2CPM
    )
) +
    geom_point(
        aes(
            shape = sample
        ),
        size = 2.5
    ) +
    facet_wrap(
        ~ gene,
        scales = "free_y",
        ncol = 5
    ) +
    labs(
        title =
            "Clean-B Anti-inflammatory-MΦ: Sham → Tx key genes",
        subtitle =
            "Sample-level SAFE pseudobulk | each point = biological sample",
        x = NULL,
        y = "log2(CPM + 1)",
        shape = "Sample"
    ) +
    theme_classic(
        base_size = 9
    ) +
    theme(
        plot.title =
            element_text(
                face = "bold"
            ),
        strip.text =
            element_text(
                face = "bold",
                size = 8
            )
    )

save_pdf(
    "01_key_gene_sample_level_pseudobulk_v4.12.0.pdf",
    p_key_gene,
    14,
    13
)

# ------------------------------------------------------------------------------
# 13. Curated program scores from pseudobulk log2CPM
#
# For each sample:
#   score = mean log2(CPM+1) across detected genes in the program.
#
# This is sample-level and avoids pseudo-replication.
# ------------------------------------------------------------------------------

PROGRAM_USE <- lapply(
    PROGRAMS,
    intersect,
    y = rownames(
        pb_log2cpm
    )
)

program_detection <- bind_rows(
    lapply(
        names(
            PROGRAMS
        ),
        function(program_name) {

            tibble(
                program = program_name,
                n_requested =
                    length(
                        PROGRAMS[[program_name]]
                    ),
                n_detected =
                    length(
                        PROGRAM_USE[[program_name]]
                    ),
                detected_genes =
                    paste(
                        PROGRAM_USE[[program_name]],
                        collapse = ";"
                    ),
                missing_genes =
                    paste(
                        setdiff(
                            PROGRAMS[[program_name]],
                            PROGRAM_USE[[program_name]]
                        ),
                        collapse = ";"
                    )
            )
        }
    )
)

write.csv(
    program_detection,
    file.path(
        TAB_DIR,
        "07_program_gene_detection_v4.12.0.csv"
    ),
    row.names = FALSE
)

program_score_rows <- list()

for (program_name in names(
    PROGRAM_USE
)) {

    genes_now <- PROGRAM_USE[[program_name]]

    if (length(genes_now) == 0L) {
        next
    }

    score_now <- colMeans(
        pb_log2cpm[
            genes_now,
            ,
            drop = FALSE
        ]
    )

    program_score_rows[[program_name]] <- tibble(
        program = program_name,
        sample = names(
            score_now
        ),
        score = as.numeric(
            score_now
        ),
        condition = ifelse(
            names(
                score_now
            ) %in%
                SHAM_SAMPLES,
            "Sham",
            "Tx"
        )
    )
}

program_scores <- bind_rows(
    program_score_rows
)

write.csv(
    program_scores,
    file.path(
        TAB_DIR,
        "08_curated_program_sample_scores_v4.12.0.csv"
    ),
    row.names = FALSE
)

program_summary <- program_scores %>%
    group_by(
        program,
        condition
    ) %>%
    summarise(
        n_samples =
            n(),
        mean_score =
            mean(score),
        min_score =
            min(score),
        max_score =
            max(score),
        .groups =
            "drop"
    )

write.csv(
    program_summary,
    file.path(
        TAB_DIR,
        "09_curated_program_condition_summary_v4.12.0.csv"
    ),
    row.names = FALSE
)

# ------------------------------------------------------------------------------
# 14. Curated-program sample plot
# ------------------------------------------------------------------------------

p_program <- ggplot(
    program_scores,
    aes(
        x = condition,
        y = score
    )
) +
    geom_point(
        aes(
            shape = sample
        ),
        size = 3
    ) +
    facet_wrap(
        ~ program,
        scales = "free_y",
        ncol = 4
    ) +
    labs(
        title =
            "Clean-B Anti-inflammatory-MΦ functional programs",
        subtitle =
            "Sample-level pseudobulk program scores; each point = biological sample",
        x = NULL,
        y = "Mean log2(CPM + 1)",
        shape = "Sample"
    ) +
    theme_classic(
        base_size = 10
    ) +
    theme(
        plot.title =
            element_text(
                face = "bold"
            ),
        strip.text =
            element_text(
                face = "bold"
            )
    )

save_pdf(
    "02_curated_functional_programs_sample_level_v4.12.0.pdf",
    p_program,
    13,
    8
)

# ------------------------------------------------------------------------------
# 15. Program delta table
# ------------------------------------------------------------------------------

program_delta <- program_summary %>%
    select(
        program,
        condition,
        mean_score
    ) %>%
    pivot_wider(
        names_from =
            condition,
        values_from =
            mean_score
    ) %>%
    mutate(
        delta_Tx_minus_Sham =
            Tx -
            Sham
    ) %>%
    arrange(
        desc(
            delta_Tx_minus_Sham
        )
    )

write.csv(
    program_delta,
    file.path(
        TAB_DIR,
        "10_curated_program_Tx_minus_Sham_delta_v4.12.0.csv"
    ),
    row.names = FALSE
)

p_program_delta <- ggplot(
    program_delta,
    aes(
        x = reorder(
            program,
            delta_Tx_minus_Sham
        ),
        y = delta_Tx_minus_Sham
    )
) +
    geom_hline(
        yintercept = 0,
        linetype = 2,
        linewidth = 0.4
    ) +
    geom_segment(
        aes(
            xend = reorder(
                program,
                delta_Tx_minus_Sham
            ),
            y = 0,
            yend =
                delta_Tx_minus_Sham
        ),
        linewidth = 0.65
    ) +
    geom_point(
        size = 3
    ) +
    coord_flip() +
    labs(
        title =
            "Anti-inflammatory-MΦ functional shift: Tx − Sham",
        subtitle =
            "Positive = higher program expression in Tx",
        x = NULL,
        y = "Mean program-score difference"
    ) +
    theme_classic(
        base_size = 10
    ) +
    theme(
        plot.title =
            element_text(
                face = "bold"
            )
    )

save_pdf(
    "03_curated_program_Tx_minus_Sham_delta_v4.12.0.pdf",
    p_program_delta,
    8,
    6
)

# ------------------------------------------------------------------------------
# 16. Volcano-like exploratory effect-size plot
# ------------------------------------------------------------------------------

if (!is.null(
    edgeR_result
)) {

    volcano_df <- edgeR_result %>%
        mutate(
            minus_log10_P =
                -log10(
                    pmax(
                        edgeR_PValue,
                        1e-300
                    )
                ),

            highlight =
                gene %in%
                    KEY_GENES_USE
        )

    p_volcano <- ggplot(
        volcano_df,
        aes(
            x = edgeR_log2FC,
            y = minus_log10_P
        )
    ) +
        geom_vline(
            xintercept = 0,
            linetype = 2,
            linewidth = 0.4
        ) +
        geom_point(
            alpha = 0.45,
            size = 1.2
        ) +
        geom_point(
            data = volcano_df %>%
                filter(
                    highlight
                ),
            size = 2.4
        ) +
        labs(
            title =
                "Clean-B Anti-inflammatory-MΦ Sham vs Tx pseudobulk",
            subtitle =
                "Exploratory edgeR; n=2 Sham vs n=2 Tx",
            x =
                "edgeR log2FC (Tx / Sham)",
            y =
                "-log10(P)"
        ) +
        theme_classic(
            base_size = 10
        ) +
        theme(
            plot.title =
                element_text(
                    face = "bold"
                )
        )

    save_pdf(
        "04_edgeR_exploratory_volcano_v4.12.0.pdf",
        p_volcano,
        8,
        7
    )
}

# ------------------------------------------------------------------------------
# 17. Optional GSEA
#
# Requires:
#   BiocManager::install("fgsea")
#   install.packages("msigdbr")
#
# GSEA is exploratory because n=2 vs 2.
# ------------------------------------------------------------------------------

gsea_completed <- FALSE

if (
    HAS_FGSEA &&
    HAS_MSIGDBR &&
    !is.null(
        edgeR_result
    )
) {

    msg(
        "Running optional Hallmark / Reactome GSEA..."
    )

    suppressPackageStartupMessages({
        library(fgsea)
        library(msigdbr)
    })

    # Rank by edgeR signed evidence.
    ranked_df <- edgeR_result %>%
        filter(
            is.finite(
                edgeR_log2FC
            ),
            is.finite(
                edgeR_PValue
            )
        ) %>%
        mutate(
            rank_score =
                sign(
                    edgeR_log2FC
                ) *
                -log10(
                    pmax(
                        edgeR_PValue,
                        1e-300
                    )
                )
        ) %>%
        arrange(
            desc(
                abs(
                    rank_score
                )
            )
        ) %>%
        distinct(
            gene,
            .keep_all = TRUE
        )

    ranks <- ranked_df$rank_score
    names(ranks) <- ranked_df$gene
    ranks <- sort(
        ranks,
        decreasing = TRUE
    )

    # Hallmark.
    hallmark_raw <- tryCatch(
        msigdbr::msigdbr(
            species = "Mus musculus",
            collection = "H"
        ),
        error = function(e) NULL
    )

    # Older msigdbr compatibility.
    if (is.null(hallmark_raw)) {
        hallmark_raw <- tryCatch(
            msigdbr::msigdbr(
                species = "Mus musculus",
                category = "H"
            ),
            error = function(e) NULL
        )
    }

    if (!is.null(hallmark_raw)) {

        hallmark_pathways <- split(
            hallmark_raw$gene_symbol,
            hallmark_raw$gs_name
        )

        fg_h <- fgsea::fgsea(
            pathways = hallmark_pathways,
            stats = ranks,
            minSize = 10,
            maxSize = 500,
            eps = 0
        ) %>%
            as_tibble() %>%
            arrange(
                padj
            )

        write.csv(
            fg_h,
            file.path(
                TAB_DIR,
                "11_GSEA_Hallmark_v4.12.0.csv"
            ),
            row.names = FALSE
        )

        top_h <- fg_h %>%
            filter(
                is.finite(NES)
            ) %>%
            arrange(
                padj,
                desc(
                    abs(NES)
                )
            ) %>%
            slice_head(
                n = 20
            )

        p_gsea_h <- ggplot(
            top_h,
            aes(
                x = NES,
                y = reorder(
                    pathway,
                    NES
                )
            )
        ) +
            geom_vline(
                xintercept = 0,
                linetype = 2,
                linewidth = 0.4
            ) +
            geom_point(
                aes(
                    size =
                        -log10(
                            pmax(
                                padj,
                                1e-300
                            )
                        )
                )
            ) +
            labs(
                title =
                    "Hallmark GSEA: Anti-inflammatory-MΦ Tx vs Sham",
                subtitle =
                    "Positive NES = enriched in Tx",
                x = "NES",
                y = NULL,
                size = "-log10(FDR)"
            ) +
            theme_classic(
                base_size = 9
            ) +
            theme(
                plot.title =
                    element_text(
                        face = "bold"
                    )
            )

        save_pdf(
            "05_GSEA_Hallmark_v4.12.0.pdf",
            p_gsea_h,
            9,
            7
        )

        gsea_completed <- TRUE
    }

    # Reactome if available through msigdbr.
    reactome_raw <- tryCatch(
        msigdbr::msigdbr(
            species = "Mus musculus",
            collection = "C2",
            subcollection = "CP:REACTOME"
        ),
        error = function(e) NULL
    )

    if (is.null(reactome_raw)) {
        reactome_raw <- tryCatch(
            msigdbr::msigdbr(
                species = "Mus musculus",
                category = "C2",
                subcategory = "CP:REACTOME"
            ),
            error = function(e) NULL
        )
    }

    if (!is.null(reactome_raw)) {

        reactome_pathways <- split(
            reactome_raw$gene_symbol,
            reactome_raw$gs_name
        )

        fg_r <- fgsea::fgsea(
            pathways = reactome_pathways,
            stats = ranks,
            minSize = 10,
            maxSize = 500,
            eps = 0
        ) %>%
            as_tibble() %>%
            arrange(
                padj
            )

        write.csv(
            fg_r,
            file.path(
                TAB_DIR,
                "12_GSEA_Reactome_v4.12.0.csv"
            ),
            row.names = FALSE
        )

        top_r <- fg_r %>%
            filter(
                is.finite(NES)
            ) %>%
            arrange(
                padj,
                desc(
                    abs(NES)
                )
            ) %>%
            slice_head(
                n = 25
            )

        p_gsea_r <- ggplot(
            top_r,
            aes(
                x = NES,
                y = reorder(
                    pathway,
                    NES
                )
            )
        ) +
            geom_vline(
                xintercept = 0,
                linetype = 2,
                linewidth = 0.4
            ) +
            geom_point(
                aes(
                    size =
                        -log10(
                            pmax(
                                padj,
                                1e-300
                            )
                        )
                )
            ) +
            labs(
                title =
                    "Reactome GSEA: Anti-inflammatory-MΦ Tx vs Sham",
                subtitle =
                    "Positive NES = enriched in Tx",
                x = "NES",
                y = NULL,
                size = "-log10(FDR)"
            ) +
            theme_classic(
                base_size = 8.5
            ) +
            theme(
                plot.title =
                    element_text(
                        face = "bold"
                    )
            )

        save_pdf(
            "06_GSEA_Reactome_v4.12.0.pdf",
            p_gsea_r,
            10,
            8
        )

        gsea_completed <- TRUE
    }

} else {

    msg(
        paste0(
            "Optional GSEA skipped. ",
            "Need edgeR + fgsea + msigdbr."
        )
    )
}

# ------------------------------------------------------------------------------
# 18. Sample-to-sample correlation
# ------------------------------------------------------------------------------

variable_genes <- rownames(
    pb_log2cpm
)[
    apply(
        pb_log2cpm,
        1,
        var
    ) > 0
]

cor_mat <- cor(
    pb_log2cpm[
        variable_genes,
        ,
        drop = FALSE
    ],
    method = "pearson"
)

write.csv(
    cor_mat,
    file.path(
        TAB_DIR,
        "13_pseudobulk_sample_correlation_v4.12.0.csv"
    )
)

cor_df <- as.data.frame(
    as.table(
        cor_mat
    )
)

colnames(
    cor_df
) <- c(
    "Sample1",
    "Sample2",
    "Correlation"
)

p_cor <- ggplot(
    cor_df,
    aes(
        x = Sample1,
        y = Sample2,
        fill = Correlation
    )
) +
    geom_tile() +
    geom_text(
        aes(
            label =
                sprintf(
                    "%.3f",
                    Correlation
                )
        ),
        size = 4
    ) +
    scale_fill_gradient(
        low = "white",
        high = "black",
        limits = c(
            min(
                cor_mat
            ),
            1
        )
    ) +
    labs(
        title =
            "Anti-inflammatory-MΦ pseudobulk sample correlation",
        x = NULL,
        y = NULL
    ) +
    theme_classic(
        base_size = 10
    ) +
    theme(
        plot.title =
            element_text(
                face = "bold"
            )
    )

save_pdf(
    "07_pseudobulk_sample_correlation_v4.12.0.pdf",
    p_cor,
    6,
    5.5
)

# ------------------------------------------------------------------------------
# 19. Master summary
# ------------------------------------------------------------------------------

summary_plots <- list(
    p_key_gene,
    p_program,
    p_program_delta,
    p_cor
)

if (exists(
    "p_volcano"
)) {
    summary_plots <- append(
        summary_plots,
        list(
            p_volcano
        )
    )
}

p_summary <- wrap_plots(
    summary_plots,
    ncol = 1
) +
    plot_annotation(
        title =
            "Clean-B Anti-inflammatory-MΦ Sham → Tx deep analysis v4.12.0",
        subtitle =
            "SAFE sample-level pseudobulk; effect size + biological replicate consistency",
        theme =
            theme(
                plot.title =
                    element_text(
                        face = "bold",
                        size = 18
                    )
            )
    )

save_pdf(
    "08_CleanB_Anti_inflammatory_Mphi_master_summary_v4.12.0.pdf",
    p_summary,
    15,
    34
)

# ------------------------------------------------------------------------------
# 20. README
# ------------------------------------------------------------------------------

readme <- c(

    "Clean-B Anti-inflammatory-MΦ Sham vs Tx deep analysis v4.12.0",
    "",

    paste0(
        "Input: ",
        INPUT_RDS
    ),
    "",

    "Primary dataset:",
    "  Clean-B from v4.11.7",
    "  Res2 cluster 24 and 27 removed",
    "  v4.8.4 MΦ annotation unchanged",
    "",

    "Biological samples:",
    "  Sham: Sham1, Sham20",
    "  Tx  : Tx17, Tx5",
    "",

    "Pseudobulk:",
    "  Explicit Matrix::rowSums(raw counts) per biological sample",
    "  n = 2 Sham vs n = 2 Tx",
    "  effect size and replicate consistency are primary",
    "  edgeR statistics are exploratory",
    "",

    paste0(
        "edgeR available: ",
        HAS_EDGER
    ),

    paste0(
        "fgsea available: ",
        HAS_FGSEA
    ),

    paste0(
        "msigdbr available: ",
        HAS_MSIGDBR
    ),

    paste0(
        "GSEA completed: ",
        gsea_completed
    ),
    "",

    "Curated programs:",
    "  Anti-inflammatory",
    "  IL10/STAT3",
    "  Efferocytosis",
    "  Repair/Resolution",
    "  Fibrogenic",
    "  Inflammatory",
    "  Lipid/TREM2",
    "",

    "Primary outputs:",
    "  01 key-gene sample-level pseudobulk",
    "  02 curated functional programs",
    "  03 program Tx-Sham delta",
    "  04 exploratory edgeR volcano (if edgeR installed)",
    "  05 Hallmark GSEA (optional)",
    "  06 Reactome GSEA (optional)",
    "  07 sample correlation",
    "  08 master summary",
    "",

    "Interpretation:",
    "  Use this analysis to determine what the expanded/recovered",
    "  Anti-inflammatory-MΦ population is functionally doing after Tx.",
    "  This is the immediate bridge to MΦ-HSC interaction analysis."
)

writeLines(
    readme,
    file.path(
        OUTPUT_DIR,
        "README_v4.12.0.txt"
    )
)

capture.output(
    sessionInfo(),
    file = file.path(
        LOG_DIR,
        "sessionInfo_v4.12.0.txt"
    )
)

# ------------------------------------------------------------------------------
# 21. Final
# ------------------------------------------------------------------------------

msg(
    "DONE."
)

msg(
    "Output: ",
    OUTPUT_DIR
)

msg(
    "edgeR exploratory: ",
    ifelse(
        HAS_EDGER,
        "ON",
        "OFF"
    )
)

msg(
    "GSEA: ",
    ifelse(
        gsea_completed,
        "completed",
        "not run"
    )
)
