#!/usr/bin/env Rscript

options(stringsAsFactors = FALSE)
set.seed(6220)

suppressPackageStartupMessages({
  library(CellChat)
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(ggplot2)
})

# ==============================================================================
# Mouse MASH scRNA-seq
# Replicate-aware CellChat refinement
#
# Version: v6.2.2
#
# INPUT
#   Four sample-wise CellChat objects generated by v6.2.1:
#     CellChat_Sham1_v6.2.1.rds
#     CellChat_Sham20_v6.2.1.rds
#     CellChat_Tx17_v6.2.1.rds
#     CellChat_Tx5_v6.2.1.rds
#
# PURPOSE
#   Refine the v6.2.1 Mphi -> HSC CellChat analysis without rerunning CellChat.
#
# KEY IMPROVEMENTS
#   1) Explicitly retain CellChat p-values and mark p < 0.05 as supported.
#   2) Keep raw probability and supported probability separately.
#   3) Use absolute delta communication probability as the PRIMARY effect size.
#   4) Avoid interpreting huge log2 ratios caused by zero probabilities.
#   5) Classify zero-to-positive and positive-to-zero changes as Tx_gain / Tx_loss.
#   6) Assess direction consistency using all 2 x 2 Tx-vs-Sham replicate pairs.
#   7) Preserve support counts in Sham and Tx biological replicates.
#   8) Produce dedicated priority-pathway and mechanistic-focus tables.
#
# PRIMARY BIOLOGICAL QUESTION
#   Does transplantation remodel macrophage -> HSC signaling, especially:
#
#     ECM-associated inflammatory-Mphi
#       -> qHSC
#       -> ECM-activated HSC
#       -> Contractile HSC
#
#   and:
#
#     Anti-inflammatory-Mphi / Repair-Resolution-Mphi
#       -> HSC states
#
# IMPORTANT
#   This is an exploratory replicate-aware analysis with n = 2 Sham and n = 2 Tx.
#   No formal group-level p-value is generated from n = 2 biological replicates.
# ==============================================================================


# ==============================================================================
# 1. Helpers
# ==============================================================================

msg <- function(...) {
  message(
    "[",
    format(Sys.time(), "%Y-%m-%d %H:%M:%S"),
    "] ",
    paste0(...)
  )
}

save_pdf <- function(
  p,
  file,
  width,
  height
) {
  grDevices::pdf(
    file,
    width = width,
    height = height,
    useDingbats = FALSE
  )
  print(p)
  grDevices::dev.off()
}

make_interaction_key <- function(df) {

  if (
    "interaction_name_2" %in%
      colnames(df)
  ) {
    return(
      as.character(
        df$interaction_name_2
      )
    )
  }

  if (
    "interaction_name" %in%
      colnames(df)
  ) {
    return(
      as.character(
        df$interaction_name
      )
    )
  }

  if (
    all(
      c(
        "ligand",
        "receptor"
      ) %in%
        colnames(df)
    )
  ) {
    return(
      paste(
        df$ligand,
        df$receptor,
        sep = " -> "
      )
    )
  }

  paste0(
    "interaction_",
    seq_len(
      nrow(df)
    )
  )
}

extract_lr_all <- function(
  cellchat,
  sample_name,
  sources,
  targets,
  p_support = 0.05
) {

  # thresh = 1 is used ONLY to expose the full inferred LR table.
  # Significance filtering is done explicitly below from the pval column.
  df <- subsetCommunication(
    cellchat,
    sources.use = sources,
    targets.use = targets,
    thresh = 1
  )

  if (
    is.null(df) ||
    !nrow(df)
  ) {
    return(
      tibble()
    )
  }

  df <- as_tibble(
    df
  )

  if (
    !"pval" %in%
      colnames(df)
  ) {
    stop(
      "CellChat subsetCommunication output does not contain 'pval'."
    )
  }

  if (
    !"prob" %in%
      colnames(df)
  ) {
    stop(
      "CellChat subsetCommunication output does not contain 'prob'."
    )
  }

  df$interaction_key <-
    make_interaction_key(
      df
    )

  df$sample <-
    sample_name

  df$condition <-
    ifelse(
      grepl(
        "^Sham",
        sample_name
      ),
      "Sham",
      "Tx"
    )

  df$supported_p05 <-
    is.finite(
      df$pval
    ) &
      df$pval <
        p_support

  df$prob_raw <-
    df$prob

  df$prob_supported <-
    ifelse(
      df$supported_p05,
      df$prob,
      0
    )

  df
}

extract_pathway_netp <- function(
  cellchat,
  sample_name,
  sources,
  targets,
  p_support = 0.05
) {

  df <- tryCatch(
    subsetCommunication(
      cellchat,
      slot.name = "netP",
      sources.use = sources,
      targets.use = targets,
      thresh = 1
    ),
    error = function(e) {
      NULL
    }
  )

  if (
    is.null(df) ||
    !nrow(df)
  ) {
    return(
      tibble()
    )
  }

  df <- as_tibble(
    df
  )

  if (
    !"prob" %in%
      colnames(df)
  ) {
    return(
      tibble()
    )
  }

  pathway_col <- intersect(
    c(
      "pathway_name",
      "pathway"
    ),
    colnames(df)
  )

  if (
    !length(
      pathway_col
    )
  ) {
    return(
      tibble()
    )
  }

  if (
    pathway_col[[1]] !=
      "pathway_name"
  ) {
    df$pathway_name <-
      as.character(
        df[[
          pathway_col[[1]]
        ]]
      )
  }

  if (
    !"pval" %in%
      colnames(df)
  ) {
    df$pval <-
      NA_real_
  }

  df$sample <-
    sample_name

  df$condition <-
    ifelse(
      grepl(
        "^Sham",
        sample_name
      ),
      "Sham",
      "Tx"
    )

  df$supported_p05 <-
    ifelse(
      is.finite(
        df$pval
      ),
      df$pval <
        p_support,
      df$prob > 0
    )

  df$prob_raw <-
    df$prob

  df$prob_supported <-
    ifelse(
      df$supported_p05,
      df$prob,
      0
    )

  df
}

direction_metrics <- function(
  sham1,
  sham20,
  tx17,
  tx5,
  tolerance = 1e-15
) {

  d1 <- tx17 - sham1
  d2 <- tx17 - sham20
  d3 <- tx5 - sham1
  d4 <- tx5 - sham20

  diffs <- c(
    d1,
    d2,
    d3,
    d4
  )

  up_n <- sum(
    diffs >
      tolerance
  )

  down_n <- sum(
    diffs <
      -tolerance
  )

  tie_n <- 4 -
    up_n -
    down_n

  direction <- dplyr::case_when(
    up_n >
      down_n ~
      "Tx_up",

    down_n >
      up_n ~
      "Tx_down",

    TRUE ~
      "Mixed_or_tied"
  )

  consistency <-
    max(
      up_n,
      down_n
    ) / 4

  tibble(
    Tx17_minus_Sham1 = d1,
    Tx17_minus_Sham20 = d2,
    Tx5_minus_Sham1 = d3,
    Tx5_minus_Sham20 = d4,
    pairwise_up_n = up_n,
    pairwise_down_n = down_n,
    pairwise_tie_n = tie_n,
    pairwise_direction = direction,
    pairwise_direction_consistency = consistency
  )
}

refine_four_sample_table <- function(
  df,
  key_cols,
  p_support = 0.05
) {

  SAMPLES_LOCAL <- c(
    "Sham1",
    "Sham20",
    "Tx17",
    "Tx5"
  )

  all_keys <- df %>%
    distinct(
      across(
        all_of(
          key_cols
        )
      )
    )

  grid <- tidyr::crossing(
    all_keys,
    sample = SAMPLES_LOCAL
  )

  sample_values <- df %>%
    group_by(
      across(
        all_of(
          key_cols
        )
      ),
      sample
    ) %>%
    summarise(
      prob_raw =
        sum(
          prob_raw,
          na.rm = TRUE
        ),

      prob_supported =
        sum(
          prob_supported,
          na.rm = TRUE
        ),

      supported_p05 =
        any(
          supported_p05,
          na.rm = TRUE
        ),

      min_pval =
        if (
          all(
            is.na(
              pval
            )
          )
        ) {
          NA_real_
        } else {
          min(
            pval,
            na.rm = TRUE
          )
        },

      .groups = "drop"
    )

  complete_df <- grid %>%
    left_join(
      sample_values,
      by = c(
        key_cols,
        "sample"
      )
    ) %>%
    mutate(
      prob_raw =
        replace_na(
          prob_raw,
          0
        ),

      prob_supported =
        replace_na(
          prob_supported,
          0
        ),

      supported_p05 =
        replace_na(
          supported_p05,
          FALSE
        ),

      min_pval =
        replace_na(
          min_pval,
          1
        )
    )

  wide <- complete_df %>%
    pivot_wider(
      names_from = sample,
      values_from = c(
        prob_raw,
        prob_supported,
        supported_p05,
        min_pval
      ),
      names_glue = "{.value}_{sample}"
    )

  direction_list <- lapply(
    seq_len(
      nrow(
        wide
      )
    ),
    function(i) {

      direction_metrics(
        sham1 =
          wide$prob_supported_Sham1[[i]],
        sham20 =
          wide$prob_supported_Sham20[[i]],
        tx17 =
          wide$prob_supported_Tx17[[i]],
        tx5 =
          wide$prob_supported_Tx5[[i]]
      )
    }
  ) %>%
    bind_rows()

  out <- bind_cols(
    wide,
    direction_list
  ) %>%
    mutate(

      Sham_mean_raw =
        (
          prob_raw_Sham1 +
            prob_raw_Sham20
        ) / 2,

      Tx_mean_raw =
        (
          prob_raw_Tx17 +
            prob_raw_Tx5
        ) / 2,

      delta_prob_raw =
        Tx_mean_raw -
          Sham_mean_raw,

      Sham_mean_supported =
        (
          prob_supported_Sham1 +
            prob_supported_Sham20
        ) / 2,

      Tx_mean_supported =
        (
          prob_supported_Tx17 +
            prob_supported_Tx5
        ) / 2,

      delta_prob_supported =
        Tx_mean_supported -
          Sham_mean_supported,

      max_condition_mean_supported =
        pmax(
          Sham_mean_supported,
          Tx_mean_supported
        ),

      relative_delta_supported =
        ifelse(
          max_condition_mean_supported >
            0,
          delta_prob_supported /
            max_condition_mean_supported,
          0
        ),

      # log2 is reported ONLY when both condition means are positive.
      # It is not used as the primary ranking metric.
      log2_Tx_vs_Sham_nonzero =
        ifelse(
          Sham_mean_supported >
            0 &
            Tx_mean_supported >
              0,
          log2(
            Tx_mean_supported /
              Sham_mean_supported
          ),
          NA_real_
        ),

      Sham_support_replicates =
        as.integer(
          supported_p05_Sham1
        ) +
          as.integer(
            supported_p05_Sham20
          ),

      Tx_support_replicates =
        as.integer(
          supported_p05_Tx17
        ) +
          as.integer(
            supported_p05_Tx5
          ),

      total_support_replicates =
        Sham_support_replicates +
          Tx_support_replicates,

      support_pattern = case_when(

        Tx_support_replicates ==
          2 &
          Sham_support_replicates ==
            0 ~
          "Tx_gain_both_replicates",

        Sham_support_replicates ==
          2 &
          Tx_support_replicates ==
            0 ~
          "Tx_loss_both_replicates",

        Tx_support_replicates >
          0 &
          Sham_support_replicates ==
            0 ~
          "Tx_gain_partial",

        Sham_support_replicates >
          0 &
          Tx_support_replicates ==
            0 ~
          "Tx_loss_partial",

        Tx_support_replicates >
          0 &
          Sham_support_replicates >
            0 ~
          "Supported_both_conditions",

        TRUE ~
          "Unsupported"
      ),

      refined_direction = case_when(

        delta_prob_supported >
          0 ~
          "Tx_up",

        delta_prob_supported <
          0 ~
          "Tx_down",

        TRUE ~
          "No_supported_change"
      ),

      confidence_class = case_when(

        support_pattern ==
          "Tx_gain_both_replicates" &
          pairwise_direction_consistency ==
            1 ~
          "Strong_Tx_gain",

        support_pattern ==
          "Tx_loss_both_replicates" &
          pairwise_direction_consistency ==
            1 ~
          "Strong_Tx_loss",

        support_pattern ==
          "Supported_both_conditions" &
          refined_direction ==
            "Tx_up" &
          pairwise_direction_consistency ==
            1 ~
          "Replicate_consistent_Tx_up",

        support_pattern ==
          "Supported_both_conditions" &
          refined_direction ==
            "Tx_down" &
          pairwise_direction_consistency ==
            1 ~
          "Replicate_consistent_Tx_down",

        pairwise_direction_consistency >=
          0.75 &
          total_support_replicates >=
            2 ~
          "Moderate_replicate_support",

        total_support_replicates >=
          1 ~
          "Limited_support",

        TRUE ~
          "Unsupported"
      ),

      refinement_rank_score =
        abs(
          delta_prob_supported
        ) *
          (
            0.5 +
              0.5 *
                pairwise_direction_consistency
          ) *
          (
            1 +
              total_support_replicates /
                4
          )
    )

  out
}

priority_pathway_flag <- function(x) {

  grepl(
    paste(
      c(
        "^TGF",
        "TGFB",
        "THBS",
        "SPP1",
        "PDGF",
        "FN1",
        "APP",
        "SEMA4",
        "GAS",
        "MERTK",
        "AXL",
        "IL10",
        "TNF",
        "CCL",
        "CXCL",
        "VEGF",
        "FGF",
        "IGF",
        "COLLAGEN",
        "LAMININ"
      ),
      collapse = "|"
    ),
    x,
    ignore.case = TRUE
  )
}


# ==============================================================================
# 2. Paths
# ==============================================================================

ROOT <-
  "/Volumes/SSD990_uenoy/scRNA_MASLD_MASH_pseudobulk"

V621 <- file.path(
  ROOT,
  "Mouse_MASH_Interaction",
  "Mphi5_HSC3_CellChat_v6.2.1"
)

INPUT_RDS_DIR <- file.path(
  V621,
  "RDS"
)

OUT <- file.path(
  ROOT,
  "Mouse_MASH_Interaction",
  "Mphi5_HSC3_CellChat_refined_v6.2.2"
)

TAB_OUT <- file.path(
  OUT,
  "Tables"
)

FIG_OUT <- file.path(
  OUT,
  "Figures"
)

LOG_OUT <- file.path(
  OUT,
  "Logs"
)

RDS_OUT <- file.path(
  OUT,
  "RDS"
)

for (
  d in c(
    OUT,
    TAB_OUT,
    FIG_OUT,
    LOG_OUT,
    RDS_OUT
  )
) {
  dir.create(
    d,
    recursive = TRUE,
    showWarnings = FALSE
  )
}


# ==============================================================================
# 3. Settings
# ==============================================================================

SAMPLES <- c(
  "Sham1",
  "Sham20",
  "Tx17",
  "Tx5"
)

SENDERS <- c(
  "Anti-inflammatory-Mphi",
  "Inflammatory-Mphi",
  "ECM-associated inflammatory-Mphi",
  "Repair/Resolution-Mphi",
  "Lipid-associated/TREM2-Mphi"
)

RECEIVERS <- c(
  "qHSC",
  "ECM-activated HSC",
  "Contractile HSC"
)

P_SUPPORT <- 0.05

CELLCHAT_FILES <- setNames(
  file.path(
    INPUT_RDS_DIR,
    paste0(
      "CellChat_",
      SAMPLES,
      "_v6.2.1.rds"
    )
  ),
  SAMPLES
)


# ==============================================================================
# 4. Preflight
# ==============================================================================

missing_files <- CELLCHAT_FILES[
  !file.exists(
    CELLCHAT_FILES
  )
]

if (
  length(
    missing_files
  )
) {
  stop(
    "Missing v6.2.1 sample-wise CellChat RDS:\n",
    paste(
      missing_files,
      collapse = "\n"
    )
  )
}

cellchat_version <-
  as.character(
    packageVersion(
      "CellChat"
    )
  )

msg(
  "CellChat version: ",
  cellchat_version
)

msg(
  "p-value support threshold: ",
  P_SUPPORT
)


# ==============================================================================
# 5. Load and extract sample-wise LR / pathway tables
# ==============================================================================

cellchat_objects <- list()
lr_list <- list()
netp_list <- list()

for (
  sample_name in SAMPLES
) {

  msg(
    "Loading ",
    sample_name
  )

  cc <- readRDS(
    CELLCHAT_FILES[[
      sample_name
    ]]
  )

  cellchat_objects[[
    sample_name
  ]] <- cc

  lr_now <- extract_lr_all(
    cellchat = cc,
    sample_name = sample_name,
    sources = SENDERS,
    targets = RECEIVERS,
    p_support = P_SUPPORT
  )

  if (
    nrow(
      lr_now
    )
  ) {
    lr_list[[
      sample_name
    ]] <- lr_now
  }

  netp_now <- extract_pathway_netp(
    cellchat = cc,
    sample_name = sample_name,
    sources = SENDERS,
    targets = RECEIVERS,
    p_support = P_SUPPORT
  )

  if (
    nrow(
      netp_now
    )
  ) {
    netp_list[[
      sample_name
    ]] <- netp_now
  }
}

if (
  !length(
    lr_list
  )
) {
  stop(
    "No LR interactions could be extracted from v6.2.1 CellChat objects."
  )
}

lr_all <- bind_rows(
  lr_list
)

write.csv(
  lr_all,
  file.path(
    TAB_OUT,
    "01_LR_all_samples_with_pvalue_v6.2.2.csv"
  ),
  row.names = FALSE
)

lr_supported <- lr_all %>%
  filter(
    supported_p05
  )

write.csv(
  lr_supported,
  file.path(
    TAB_OUT,
    "02_LR_CellChat_p05_supported_only_v6.2.2.csv"
  ),
  row.names = FALSE
)

msg(
  "All extracted LR rows: ",
  nrow(
    lr_all
  )
)

msg(
  "p < 0.05 supported LR rows: ",
  nrow(
    lr_supported
  )
)


# ==============================================================================
# 6. LR-level refined comparison
# ==============================================================================

for (
  nm in c(
    "ligand",
    "receptor",
    "pathway_name"
  )
) {
  if (
    !nm %in%
      colnames(
        lr_all
      )
  ) {
    lr_all[[nm]] <-
      NA_character_
  }
}

lr_keys <- c(
  "source",
  "target",
  "pathway_name",
  "interaction_key",
  "ligand",
  "receptor"
)

lr_refined <- refine_four_sample_table(
  df = lr_all,
  key_cols = lr_keys,
  p_support = P_SUPPORT
) %>%
  mutate(
    priority_pathway =
      priority_pathway_flag(
        pathway_name
      )
  ) %>%
  arrange(
    desc(
      refinement_rank_score
    )
  )

write.csv(
  lr_refined,
  file.path(
    TAB_OUT,
    "03_LR_refined_replicate_comparison_v6.2.2.csv"
  ),
  row.names = FALSE
)

lr_priority <- lr_refined %>%
  filter(
    priority_pathway,
    total_support_replicates >=
      1
  ) %>%
  arrange(
    desc(
      refinement_rank_score
    )
  )

write.csv(
  lr_priority,
  file.path(
    TAB_OUT,
    "04_LR_priority_pathways_refined_v6.2.2.csv"
  ),
  row.names = FALSE
)


# ==============================================================================
# 7. Pathway-level refined comparison
#
# Primary pathway metric:
#   sum of p < 0.05-supported LR probabilities within each
#   sample x sender x receiver x pathway.
#
# This remains directly traceable to the LR interactions used above.
# ==============================================================================

pathway_from_lr <- lr_all %>%
  group_by(
    sample,
    condition,
    source,
    target,
    pathway_name
  ) %>%
  summarise(
    prob_raw =
      sum(
        prob_raw,
        na.rm = TRUE
      ),

    prob_supported =
      sum(
        prob_supported,
        na.rm = TRUE
      ),

    supported_p05 =
      any(
        supported_p05,
        na.rm = TRUE
      ),

    pval =
      if (
        all(
          is.na(
            pval
          )
        )
      ) {
        NA_real_
      } else {
        min(
          pval,
          na.rm = TRUE
        )
      },

    n_LR_total =
      n_distinct(
        interaction_key
      ),

    n_LR_supported =
      n_distinct(
        interaction_key[
          supported_p05
        ]
      ),

    .groups = "drop"
  )

write.csv(
  pathway_from_lr,
  file.path(
    TAB_OUT,
    "05_pathway_supported_LR_strength_by_sample_v6.2.2.csv"
  ),
  row.names = FALSE
)

pathway_refined <- refine_four_sample_table(
  df = pathway_from_lr,
  key_cols = c(
    "source",
    "target",
    "pathway_name"
  ),
  p_support = P_SUPPORT
) %>%
  mutate(
    priority_pathway =
      priority_pathway_flag(
        pathway_name
      )
  ) %>%
  arrange(
    desc(
      priority_pathway
    ),
    desc(
      refinement_rank_score
    )
  )

write.csv(
  pathway_refined,
  file.path(
    TAB_OUT,
    "06_pathway_refined_replicate_comparison_v6.2.2.csv"
  ),
  row.names = FALSE
)

priority_pathway_refined <- pathway_refined %>%
  filter(
    priority_pathway,
    total_support_replicates >=
      1
  ) %>%
  arrange(
    desc(
      refinement_rank_score
    )
  )

write.csv(
  priority_pathway_refined,
  file.path(
    TAB_OUT,
    "07_priority_pathways_refined_v6.2.2.csv"
  ),
  row.names = FALSE
)


# ==============================================================================
# 8. Optional CellChat netP audit
# ==============================================================================

if (
  length(
    netp_list
  )
) {

  netp_all <- bind_rows(
    netp_list
  )

  write.csv(
    netp_all,
    file.path(
      TAB_OUT,
      "08_CellChat_netP_pathway_audit_v6.2.2.csv"
    ),
    row.names = FALSE
  )

} else {

  writeLines(
    "CellChat netP pathway table was not available through subsetCommunication(slot.name='netP'). Primary pathway summaries use the sum of p<0.05-supported LR probabilities.",
    con = file.path(
      LOG_OUT,
      "netP_extraction_note_v6.2.2.txt"
    )
  )
}


# ==============================================================================
# 9. ECM-associated inflammatory-Mphi -> HSC focus
# ==============================================================================

ecm_lr_focus <- lr_refined %>%
  filter(
    source ==
      "ECM-associated inflammatory-Mphi",
    target %in%
      RECEIVERS,
    total_support_replicates >=
      1
  ) %>%
  arrange(
    target,
    desc(
      refinement_rank_score
    )
  )

write.csv(
  ecm_lr_focus,
  file.path(
    TAB_OUT,
    "09_ECM_inflammatory_Mphi_to_HSC3_LR_refined_v6.2.2.csv"
  ),
  row.names = FALSE
)

ecm_pathway_focus <- pathway_refined %>%
  filter(
    source ==
      "ECM-associated inflammatory-Mphi",
    target %in%
      RECEIVERS,
    total_support_replicates >=
      1
  ) %>%
  arrange(
    target,
    desc(
      priority_pathway
    ),
    desc(
      refinement_rank_score
    )
  )

write.csv(
  ecm_pathway_focus,
  file.path(
    TAB_OUT,
    "10_ECM_inflammatory_Mphi_to_HSC3_pathway_refined_v6.2.2.csv"
  ),
  row.names = FALSE
)


# ==============================================================================
# 10. Anti-inflammatory / Repair-Resolution focus
# ==============================================================================

resolution_lr_focus <- lr_refined %>%
  filter(
    source %in%
      c(
        "Anti-inflammatory-Mphi",
        "Repair/Resolution-Mphi"
      ),
    target %in%
      RECEIVERS,
    total_support_replicates >=
      1
  ) %>%
  arrange(
    source,
    target,
    desc(
      refinement_rank_score
    )
  )

write.csv(
  resolution_lr_focus,
  file.path(
    TAB_OUT,
    "11_AntiInflammatory_Repair_to_HSC3_LR_refined_v6.2.2.csv"
  ),
  row.names = FALSE
)

resolution_pathway_focus <- pathway_refined %>%
  filter(
    source %in%
      c(
        "Anti-inflammatory-Mphi",
        "Repair/Resolution-Mphi"
      ),
    target %in%
      RECEIVERS,
    total_support_replicates >=
      1
  ) %>%
  arrange(
    source,
    target,
    desc(
      priority_pathway
    ),
    desc(
      refinement_rank_score
    )
  )

write.csv(
  resolution_pathway_focus,
  file.path(
    TAB_OUT,
    "12_AntiInflammatory_Repair_to_HSC3_pathway_refined_v6.2.2.csv"
  ),
  row.names = FALSE
)


# ==============================================================================
# 11. High-confidence candidate shortlist
# ==============================================================================

HIGH_CONF_CLASSES <- c(
  "Strong_Tx_gain",
  "Strong_Tx_loss",
  "Replicate_consistent_Tx_up",
  "Replicate_consistent_Tx_down"
)

candidate_shortlist <- lr_refined %>%
  filter(
    total_support_replicates >=
      2,
    pairwise_direction_consistency >=
      0.75,
    priority_pathway |
      confidence_class %in%
        HIGH_CONF_CLASSES
  ) %>%
  mutate(
    mechanistic_focus = case_when(

      source ==
        "ECM-associated inflammatory-Mphi" ~
        "Primary_ECM-inflammatory_to_HSC",

      source %in%
        c(
          "Anti-inflammatory-Mphi",
          "Repair/Resolution-Mphi"
        ) ~
        "Resolution_axis_to_HSC",

      TRUE ~
        "Other_Mphi_to_HSC"
    )
  ) %>%
  arrange(
    desc(
      confidence_class %in%
        HIGH_CONF_CLASSES
    ),
    desc(
      priority_pathway
    ),
    desc(
      refinement_rank_score
    )
  )

write.csv(
  candidate_shortlist,
  file.path(
    TAB_OUT,
    "13_high_confidence_LR_candidate_shortlist_v6.2.2.csv"
  ),
  row.names = FALSE
)

candidate_pathway_shortlist <- pathway_refined %>%
  filter(
    total_support_replicates >=
      2,
    pairwise_direction_consistency >=
      0.75,
    priority_pathway |
      confidence_class %in%
        HIGH_CONF_CLASSES
  ) %>%
  arrange(
    desc(
      confidence_class %in%
        HIGH_CONF_CLASSES
    ),
    desc(
      priority_pathway
    ),
    desc(
      refinement_rank_score
    )
  )

write.csv(
  candidate_pathway_shortlist,
  file.path(
    TAB_OUT,
    "14_high_confidence_pathway_candidate_shortlist_v6.2.2.csv"
  ),
  row.names = FALSE
)


# ==============================================================================
# 12. Figure 1:
#     refined pathway relative-delta heatmap
#
# Bounded relative delta avoids the giant values caused by zero denominators.
# ==============================================================================

heat_df <- priority_pathway_refined %>%
  filter(
    total_support_replicates >=
      1
  ) %>%
  mutate(
    sender_receiver =
      paste0(
        source,
        " -> ",
        target
      )
  )

pathway_order <- heat_df %>%
  group_by(
    pathway_name
  ) %>%
  summarise(
    max_rank =
      max(
        refinement_rank_score,
        na.rm = TRUE
      ),
    .groups = "drop"
  ) %>%
  arrange(
    desc(
      max_rank
    )
  ) %>%
  slice_head(
    n = 30
  ) %>%
  pull(
    pathway_name
  )

heat_df <- heat_df %>%
  filter(
    pathway_name %in%
      pathway_order
  ) %>%
  mutate(
    pathway_name =
      factor(
        pathway_name,
        levels =
          rev(
            pathway_order
          )
      )
  )

if (
  nrow(
    heat_df
  )
) {

  p1 <- ggplot(
    heat_df,
    aes(
      x =
        sender_receiver,
      y =
        pathway_name,
      fill =
        relative_delta_supported
    )
  ) +
    geom_tile(
      linewidth = 0.25
    ) +
    scale_fill_gradient2(
      low = "#0033FF",
      mid = "#FFFFFF",
      high = "#FF1A1A",
      midpoint = 0,
      limits = c(
        -1,
        1
      )
    ) +
    labs(
      title =
        "Refined Mphi -> HSC pathway change",
      subtitle =
        "Relative delta of p<0.05-supported communication; red = Tx higher, blue = Tx lower",
      x = NULL,
      y = NULL,
      fill =
        "Relative delta"
    ) +
    theme_classic(
      base_size = 7
    ) +
    theme(
      axis.text.x =
        element_text(
          angle = 60,
          hjust = 1
        ),
      plot.title =
        element_text(
          face = "bold",
          hjust = 0.5
        )
    )

  save_pdf(
    p1,
    file.path(
      FIG_OUT,
      "01_refined_priority_pathway_relative_delta_heatmap_v6.2.2.pdf"
    ),
    18,
    10
  )
}


# ==============================================================================
# 13. Figure 2:
#     biological-sample supported pathway strength
# ==============================================================================

priority_sample <- pathway_from_lr %>%
  filter(
    priority_pathway_flag(
      pathway_name
    ),
    prob_supported >
      0
  ) %>%
  mutate(
    sender_receiver_pathway =
      paste0(
        source,
        " -> ",
        target,
        " | ",
        pathway_name
      )
  )

top_keys <- priority_sample %>%
  group_by(
    sender_receiver_pathway
  ) %>%
  summarise(
    max_strength =
      max(
        prob_supported,
        na.rm = TRUE
      ),
    .groups = "drop"
  ) %>%
  arrange(
    desc(
      max_strength
    )
  ) %>%
  slice_head(
    n = 40
  ) %>%
  pull(
    sender_receiver_pathway
  )

sample_plot_df <- priority_sample %>%
  filter(
    sender_receiver_pathway %in%
      top_keys
  ) %>%
  mutate(
    sample =
      factor(
        sample,
        levels = SAMPLES
      ),
    sender_receiver_pathway =
      factor(
        sender_receiver_pathway,
        levels =
          rev(
            top_keys
          )
      )
  )

if (
  nrow(
    sample_plot_df
  )
) {

  p2 <- ggplot(
    sample_plot_df,
    aes(
      x =
        sample,
      y =
        sender_receiver_pathway,
      fill =
        prob_supported
    )
  ) +
    geom_tile(
      linewidth = 0.25
    ) +
    scale_fill_gradientn(
      colours = c(
        "#0033FF",
        "#FFFFFF",
        "#FF1A1A"
      )
    ) +
    labs(
      title =
        "Priority Mphi -> HSC pathways by biological sample",
      subtitle =
        "Only p<0.05-supported LR probability contributes to pathway strength",
      x = NULL,
      y = NULL,
      fill =
        "Supported strength"
    ) +
    theme_classic(
      base_size = 7
    ) +
    theme(
      plot.title =
        element_text(
          face = "bold",
          hjust = 0.5
        )
    )

  save_pdf(
    p2,
    file.path(
      FIG_OUT,
      "02_priority_pathway_supported_strength_by_sample_v6.2.2.pdf"
    ),
    10,
    12
  )
}


# ==============================================================================
# 14. Figure 3:
#     ECM-associated inflammatory-Mphi -> HSC LR delta
# ==============================================================================

ecm_plot_df <- ecm_lr_focus %>%
  filter(
    total_support_replicates >=
      1
  ) %>%
  group_by(
    target
  ) %>%
  arrange(
    desc(
      refinement_rank_score
    ),
    .by_group = TRUE
  ) %>%
  slice_head(
    n = 20
  ) %>%
  ungroup() %>%
  mutate(
    interaction_label =
      interaction_key
  )

if (
  nrow(
    ecm_plot_df
  )
) {

  p3 <- ggplot(
    ecm_plot_df,
    aes(
      x =
        delta_prob_supported,
      y =
        reorder(
          interaction_label,
          delta_prob_supported
        ),
      size =
        max_condition_mean_supported
    )
  ) +
    geom_point() +
    geom_vline(
      xintercept = 0,
      linewidth = 0.4
    ) +
    facet_wrap(
      ~ target,
      scales = "free_y",
      ncol = 1
    ) +
    labs(
      title =
        "ECM-associated inflammatory-Mphi -> HSC",
      subtitle =
        "Absolute delta of p<0.05-supported CellChat probability",
      x =
        "Tx mean - Sham mean",
      y = NULL,
      size =
        "Max condition mean"
    ) +
    theme_classic(
      base_size = 8
    ) +
    theme(
      plot.title =
        element_text(
          face = "bold",
          hjust = 0.5
        )
    )

  save_pdf(
    p3,
    file.path(
      FIG_OUT,
      "03_ECM_inflammatory_to_HSC3_refined_LR_delta_v6.2.2.pdf"
    ),
    10,
    12
  )
}


# ==============================================================================
# 15. Figure 4:
#     top high-confidence pathway changes
# ==============================================================================

top_path_df <- candidate_pathway_shortlist %>%
  slice_head(
    n = 40
  ) %>%
  mutate(
    label =
      paste0(
        source,
        " -> ",
        target,
        " | ",
        pathway_name
      ),

    label =
      factor(
        label,
        levels =
          rev(
            unique(
              label
            )
          )
      )
  )

if (
  nrow(
    top_path_df
  )
) {

  p4 <- ggplot(
    top_path_df,
    aes(
      x =
        delta_prob_supported,
      y =
        label,
      size =
        total_support_replicates
    )
  ) +
    geom_point() +
    geom_vline(
      xintercept = 0,
      linewidth = 0.4
    ) +
    labs(
      title =
        "High-confidence Mphi -> HSC pathway candidates",
      subtitle =
        "Positive = Tx higher; negative = Tx lower",
      x =
        "Tx mean - Sham mean supported probability",
      y = NULL,
      size =
        "Supported\nreplicates"
    ) +
    theme_classic(
      base_size = 8
    )

  save_pdf(
    p4,
    file.path(
      FIG_OUT,
      "04_high_confidence_pathway_candidates_v6.2.2.pdf"
    ),
    11,
    11
  )
}


# ==============================================================================
# 16. Save compact refined data RDS
# ==============================================================================

refined_results <- list(
  lr_all =
    lr_all,
  lr_refined =
    lr_refined,
  pathway_by_sample =
    pathway_from_lr,
  pathway_refined =
    pathway_refined,
  candidate_LR =
    candidate_shortlist,
  candidate_pathways =
    candidate_pathway_shortlist
)

saveRDS(
  refined_results,
  file.path(
    RDS_OUT,
    "Mouse_MASH_Mphi5_HSC3_CellChat_refined_results_v6.2.2.rds"
  ),
  compress = FALSE
)


# ==============================================================================
# 17. Analysis manifest
# ==============================================================================

manifest <- tibble(
  parameter = c(
    "version",
    "CellChat_version",
    "input_directory",
    "p_support_threshold",
    "primary_effect_size",
    "log2_policy",
    "replicate_design",
    "n_Shams",
    "n_Tx",
    "CellChat_recomputed"
  ),
  value = c(
    "v6.2.2",
    cellchat_version,
    V621,
    as.character(
      P_SUPPORT
    ),
    "Tx_mean_supported - Sham_mean_supported",
    "Only calculated when both supported condition means are >0; not used as primary ranking",
    "All four Tx-vs-Sham pairwise comparisons retained",
    "2",
    "2",
    "FALSE"
  )
)

write.csv(
  manifest,
  file.path(
    LOG_OUT,
    "analysis_manifest_v6.2.2.csv"
  ),
  row.names = FALSE
)

capture.output(
  sessionInfo(),
  file =
    file.path(
      LOG_OUT,
      "sessionInfo_v6.2.2.txt"
    )
)

msg(
  "DONE."
)

msg(
  "Output directory: ",
  OUT
)
